export const HOME_URL = '/'
export const REGISTER_URL = '/register'
export const LOGIN_URL = '/login'
export const VIDEOGAMES_URL = '/videogames'
export const CLUB_URL = '/club'
export const PROFILE_URL = '/about'